_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 16
epochs:
    value: 5
hidden_layers:
    value: 3
hidden_size:
    value: 128
learning_rate:
    value: 0.001
optimizer:
    value: nesterov
weight_decay:
    value: 0
weight_init:
    value: xavier
