wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 5
hidden_layers:
  value: 3
hidden_size:
  value: 128
learning_rate:
  value: 0.0001
optimizer:
  value: nesterov
weight_decay:
  value: 0.0005
weight_init:
  value: random
