wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 10
hidden_layers:
  value: 3
hidden_size:
  value: 64
learning_rate:
  value: 0.0001
optimizer:
  value: nesterov
weight_decay:
  value: 0.5
weight_init:
  value: random
