wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 5
hidden_layers:
  value: 5
hidden_size:
  value: 32
learning_rate:
  value: 0.0001
optimizer:
  value: sgd
weight_decay:
  value: 0.5
weight_init:
  value: xavier
