wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 10
hidden_layers:
  value: 3
hidden_size:
  value: 32
learning_rate:
  value: 0.001
optimizer:
  value: adam
weight_decay:
  value: 0.5
weight_init:
  value: random
