wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 10
hidden_layers:
  value: 4
hidden_size:
  value: 32
learning_rate:
  value: 0.001
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
