wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 10
hidden_layers:
  value: 5
hidden_size:
  value: 64
learning_rate:
  value: 0.0001
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: xavier
