wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 5
hidden_layers:
  value: 4
hidden_size:
  value: 32
learning_rate:
  value: 0.0001
optimizer:
  value: nesterov
weight_decay:
  value: 0
weight_init:
  value: random
