_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.7
            "8":
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
activation:
    value: ReLU
batch_size:
    value: 64
beta:
    value: 0.5
beta1:
    value: 0.5
beta2:
    value: 0.999
dataset:
    value: fashion_mnist
epochs:
    value: 10
epsilon:
    value: 1e-08
hidden_layers:
    value: 5
hidden_size:
    value: 64
learning_rate:
    value: 0.001
loss_fn:
    value: cross_entropy
momentum:
    value: 0.9
optimizer:
    value: nadam
weight_decay:
    value: 0.0005
weight_init:
    value: random
