wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
beta:
  value: 0.5
beta1:
  value: 0.5
beta2:
  value: 0.999
dataset:
  value: fashion_mnist
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_layers:
  value: 5
hidden_size:
  value: 64
learning_rate:
  value: 0.001
loss_fn:
  value: cross_entropy
momentum:
  value: 0.9
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_init:
  value: random
