_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "3":
                - 2
                - 17
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.7
            "8":
                - 3
                - 5
            "10":
                - 3
            "12": 0.19.7
            "13": windows-amd64
activation:
    value: sigmoid
batch_size:
    value: 4
dataset:
    value: fashion_mnist
epochs:
    value: 1
hidden_layers:
    value: 1
hidden_size:
    value: 4
learning_rate:
    value: 0.1
loss_fn:
    value: cross_entropy
optimizer:
    value: sgd
weight_decay:
    value: 0
weight_init:
    value: random
