wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
beta:
  value: 0.5
beta1:
  value: 0.9
beta2:
  value: 0.999
dataset:
  value: fashion_mnist
epochs:
  value: 5
epsilon:
  value: 1.0e-08
hidden_layers:
  value: 4
hidden_size:
  value: 128
learning_rate:
  value: 0.0001
loss_fn:
  value: cross_entropy
momentum:
  value: 0.9
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0005
weight_init:
  value: random
