_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.7
            "8":
                - 1
                - 3
                - 5
            "10":
                - 3
            "12": 0.19.7
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 64
epochs:
    value: 10
hidden_layers:
    value: 4
hidden_size:
    value: 64
learning_rate:
    value: 0.0001
optimizer:
    value: nadam
weight_decay:
    value: 0.0005
weight_init:
    value: xavier
